import { eq, and, gte, lte, isNull } from "drizzle-orm";
import { db } from "../db.js";
import {
  deliveries,
  deliveryPrices,
  invoices,
  invoiceItems,
  shops,
  orders,
} from "../../db/schema/index.js";
import { sseManager } from "../sse/manager.js";
import { companyChannel, orderChannel } from "../sse/channels.js";

/**
 * Valid invoice status transitions.
 * draft -> sent -> paid
 */
const VALID_TRANSITIONS: Record<string, string[]> = {
  draft: ["sent"],
  sent: ["paid"],
};

export function isValidInvoiceTransition(
  currentStatus: string,
  newStatus: string
): boolean {
  return VALID_TRANSITIONS[currentStatus]?.includes(newStatus) ?? false;
}

/**
 * Generate an invoice for a shop in a period.
 * Finds delivered deliveries not linked to any existing invoice,
 * calculates totals from delivery_prices, creates invoice + items.
 */
export async function generateInvoice(params: {
  shopId: string;
  companyId: string;
  periodStart: string;
  periodEnd: string;
}) {
  const { shopId, companyId, periodStart, periodEnd } = params;

  // Fetch the shop (need trade_name for SSE event)
  const [shop] = await db
    .select()
    .from(shops)
    .where(
      and(eq(shops.id, shopId), eq(shops.company_id, companyId))
    );

  if (!shop) {
    return null;
  }

  // Find delivered deliveries for this shop in the period
  // that are NOT already linked to an invoice_item
  const eligibleDeliveries = await db
    .select({
      delivery_id: deliveries.id,
      order_id: deliveries.order_id,
      delivered_at: deliveries.delivered_at,
      total_price: deliveryPrices.total_price,
      actual_distance_km: deliveryPrices.actual_distance_km,
      estimated_distance_km: deliveryPrices.estimated_distance_km,
      order_number: orders.order_number,
      pickup_address: orders.pickup_address,
      delivery_address: orders.delivery_address,
    })
    .from(deliveries)
    .innerJoin(deliveryPrices, eq(deliveryPrices.delivery_id, deliveries.id))
    .innerJoin(orders, eq(orders.id, deliveries.order_id))
    .leftJoin(invoiceItems, eq(invoiceItems.delivery_id, deliveries.id))
    .where(
      and(
        eq(orders.shop_id, shopId),
        eq(deliveries.company_id, companyId),
        eq(deliveries.status, "delivered"),
        gte(deliveries.delivered_at, periodStart),
        lte(deliveries.delivered_at, periodEnd),
        isNull(invoiceItems.id)
      )
    );

  if (eligibleDeliveries.length === 0) {
    throw new Error(
      "No eligible deliveries found for this shop in the specified period"
    );
  }

  // Calculate totals
  let totalDistanceKm = 0;
  let totalAmount = 0;

  const items = eligibleDeliveries.map((d) => {
    const price = parseFloat(d.total_price);
    const distance = parseFloat(
      d.actual_distance_km ?? d.estimated_distance_km
    );
    totalDistanceKm += distance;
    totalAmount += price;
    return {
      delivery_id: d.delivery_id,
      order_number: d.order_number,
      pickup_address: d.pickup_address,
      delivery_address: d.delivery_address,
      distance_km: (d.actual_distance_km ?? d.estimated_distance_km).toString(),
      price: d.total_price,
      delivered_at: d.delivered_at!,
    };
  });

  const now = new Date().toISOString();

  // Create the invoice record
  // invoice_number is auto-generated by DB trigger (trg_invoices_number)
  const [invoice] = await db
    .insert(invoices)
    .values({
      company_id: companyId,
      shop_id: shopId,
      invoice_number: 0, // placeholder, overwritten by trigger
      period_start: periodStart,
      period_end: periodEnd,
      total_deliveries: eligibleDeliveries.length,
      total_distance_km: totalDistanceKm.toFixed(2),
      total_amount: totalAmount.toFixed(2),
      status: "draft",
      created_at: now,
      updated_at: now,
    })
    .returning();

  // Create invoice items
  const createdItems = await db
    .insert(invoiceItems)
    .values(
      items.map((item) => ({
        invoice_id: invoice.id,
        delivery_id: item.delivery_id,
        order_number: item.order_number,
        pickup_address: item.pickup_address,
        delivery_address: item.delivery_address,
        distance_km: item.distance_km,
        price: item.price,
        delivered_at: item.delivered_at,
      }))
    )
    .returning();

  // Emit SSE invoice_created on company channel
  sseManager
    .broadcast(companyChannel(companyId), {
      type: "invoice_created",
      invoiceId: invoice.id,
      shopId: shopId,
      shopName: shop.trade_name,
      totalAmount: invoice.total_amount,
      periodStart: invoice.period_start,
      periodEnd: invoice.period_end,
    })
    .catch(() => {});

  return { ...invoice, items: createdItems };
}

/**
 * Send an invoice (draft -> sent).
 * Emits SSE invoice_sent on company and order channels.
 */
export async function sendInvoice(params: {
  invoiceId: string;
  companyId: string;
}) {
  const { invoiceId, companyId } = params;

  const [invoice] = await db
    .select()
    .from(invoices)
    .where(
      and(
        eq(invoices.id, invoiceId),
        eq(invoices.company_id, companyId)
      )
    );

  if (!invoice) {
    return null;
  }

  if (!isValidInvoiceTransition(invoice.status, "sent")) {
    throw new Error(
      `Cannot send invoice: current status is '${invoice.status}', must be 'draft'`
    );
  }

  const now = new Date().toISOString();

  const [updated] = await db
    .update(invoices)
    .set({
      status: "sent",
      sent_at: now,
      updated_at: now,
    })
    .where(eq(invoices.id, invoiceId))
    .returning();

  // Get shop name for SSE event
  const [shop] = await db
    .select({ trade_name: shops.trade_name })
    .from(shops)
    .where(eq(shops.id, invoice.shop_id));

  const shopName = shop?.trade_name ?? "Unknown";

  // Emit SSE invoice_sent on company channel
  sseManager
    .broadcast(companyChannel(companyId), {
      type: "invoice_sent",
      invoiceId: invoice.id,
      shopId: invoice.shop_id,
      shopName,
    })
    .catch(() => {});

  // Emit SSE invoice_sent on order channel for the shop's orders
  // Get all delivery order_ids from this invoice's items
  const items = await db
    .select({ delivery_id: invoiceItems.delivery_id })
    .from(invoiceItems)
    .where(eq(invoiceItems.invoice_id, invoiceId));

  for (const item of items) {
    const [delivery] = await db
      .select({ order_id: deliveries.order_id })
      .from(deliveries)
      .where(eq(deliveries.id, item.delivery_id));

    if (delivery) {
      sseManager
        .broadcast(orderChannel(delivery.order_id), {
          type: "invoice_sent",
          invoiceId: invoice.id,
          shopName,
        })
        .catch(() => {});
    }
  }

  return updated;
}

/**
 * Pay an invoice (sent -> paid).
 * Prevents modification after paid status.
 */
export async function payInvoice(params: {
  invoiceId: string;
  companyId: string;
}) {
  const { invoiceId, companyId } = params;

  const [invoice] = await db
    .select()
    .from(invoices)
    .where(
      and(
        eq(invoices.id, invoiceId),
        eq(invoices.company_id, companyId)
      )
    );

  if (!invoice) {
    return null;
  }

  if (!isValidInvoiceTransition(invoice.status, "paid")) {
    throw new Error(
      `Cannot pay invoice: current status is '${invoice.status}', must be 'sent'`
    );
  }

  const now = new Date().toISOString();

  const [updated] = await db
    .update(invoices)
    .set({
      status: "paid",
      paid_at: now,
      updated_at: now,
    })
    .where(eq(invoices.id, invoiceId))
    .returning();

  return updated;
}

/**
 * List invoices with optional filters.
 */
export async function listInvoices(params: {
  companyId: string;
  shopId?: string;
  status?: string;
  periodStart?: string;
  periodEnd?: string;
}) {
  const { companyId, shopId, status, periodStart, periodEnd } = params;

  const conditions = [eq(invoices.company_id, companyId)];

  if (shopId) {
    conditions.push(eq(invoices.shop_id, shopId));
  }
  if (status) {
    conditions.push(
      eq(invoices.status, status as "draft" | "sent" | "paid")
    );
  }
  if (periodStart) {
    conditions.push(gte(invoices.period_start, periodStart));
  }
  if (periodEnd) {
    conditions.push(lte(invoices.period_end, periodEnd));
  }

  return db
    .select()
    .from(invoices)
    .where(and(...conditions))
    .orderBy(invoices.created_at);
}

/**
 * Get an invoice by ID with its items.
 */
export async function getInvoiceById(params: {
  invoiceId: string;
  companyId: string;
}) {
  const { invoiceId, companyId } = params;

  const [invoice] = await db
    .select()
    .from(invoices)
    .where(
      and(
        eq(invoices.id, invoiceId),
        eq(invoices.company_id, companyId)
      )
    );

  if (!invoice) {
    return null;
  }

  const items = await db
    .select()
    .from(invoiceItems)
    .where(eq(invoiceItems.invoice_id, invoiceId));

  return { ...invoice, items };
}
